version: '3.8'
services:
  app:
    image: your-dockerhub/task-master-pro:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_master_pro
    ports:
      - "5432:5432"
